sudo: required
dist: trusty
language: php

php:
  - 7.3

addons:
  chrome: stable

services:
  - mysql

cache:
  directories:
    - vendor
    - node_modules

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install
  - npm run prod

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - mysql -e 'CREATE DATABASE testing;'
  - cp .env.travis .env
  - cp .env.travis .env.testing
  - cp phpunit.travis.xml phpunit.xml
  - php artisan key:generate
  - php artisan storage:link
  - php artisan serve &

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml
  - php artisan dusk

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml
  - git checkout .

notifications:
  email: false
